import { expect, openPage, pollUntil, test } from "./support"

test("catalog shell supports route search, source copy, theme and mobile browse", async () => {
  await using page = await openPage()
  await page.grantClipboardPermission()
  await page.goto("/#button/default")
  const heading = page.getByRole("heading", { name: "Button", exact: true })
  await pollUntil(() => heading.count())
  await expect(heading).toBeVisible()
  await page.getByText("View code", { exact: true }).first().click()
  await expect(page.locator(".code-panel code").first()).toContainText("export default function Example")
  await page.getByRole("button", { name: "Copy code" }).first().click()
  await expect(page.getByRole("button", { name: "Copied", exact: true })).toBeVisible()
  await page.getByLabel("Toggle theme").click()
  await expect(page.locator("html")).not.toHaveClass("dark")
  await page.getByLabel("Find a component").fill("dialog")
  await page.getByRole("link", { name: "Dialog", exact: true }).click()
  await expect(page.getByRole("heading", { name: "Dialog", exact: true })).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole("button", { name: "Browse", exact: true }).click()
  await expect(page.getByLabel("Find a component")).toBeVisible()
  expect(await page.evaluate<boolean>(`() => document.documentElement.scrollWidth <= innerWidth`)).toBe(true)
})

test("core primitive interactions remain executable", async () => {
  await using page = await openPage()

  await page.goto("/?preview#checkbox/default")
  const checkbox = page.getByRole("checkbox")
  await pollUntil(() => checkbox.count())
  await checkbox.click()
  await expect(checkbox).toBeChecked()

  await page.goto("/?preview#select/default")
  const combobox = page.getByRole("combobox")
  await pollUntil(() => combobox.count())
  await combobox.click()
  await page.getByRole("option").first().click()
  await expect(combobox).not.toHaveText("Select role")

  await page.goto("/?preview#tabs/default")
  const tab = page.getByRole("tab", { name: "Layout packs" })
  await pollUntil(() => tab.count())
  await tab.click()
  await expect(tab).toHaveAttribute("aria-selected", "true")

  await page.goto("/?preview#toast/default")
  const showToast = page.getByRole("button", { name: "Show toast" })
  await pollUntil(() => showToast.count())
  await showToast.click()
  await expect(page.getByText("Saved", { exact: true })).toBeVisible()
})
