import { expect, test } from "@playwright/test"

for (const theme of ["light", "dark"]) {
  test(`compound focus, selection and caller geometry ${theme}`, async ({ page }) => {
    await page.goto(`/style-x?preview&theme=${theme}#combobox/default`)
    const team = page.getByRole("combobox", { name: "Team" })
    await team.fill("Eng")
    await expect(page.getByRole("option", { name: "Engineering" })).toBeVisible()
    await page.keyboard.press("ArrowDown")
    await page.keyboard.press("Enter")
    await expect(team).toHaveValue("Engineering")
    await page.goto(`/style-x?preview&theme=${theme}#drawer/default`)
    await page.getByRole("button", { name: "Open drawer" }).click()
    const drawer = page.getByRole("dialog")
    await expect(drawer).toBeVisible()
    await expect
      .poll(() => drawer.evaluate((node) => Math.round(node.getBoundingClientRect().bottom)))
      .toBe(page.viewportSize()!.height)
    expect(await drawer.evaluate((node) => getComputedStyle(node).transform)).not.toBe("none")
    await page.keyboard.press("Escape")
    await expect(drawer).toHaveCount(0)
    await expect(page.getByRole("button", { name: "Open drawer" })).toBeFocused()
    await page.goto(`/style-x?preview&theme=${theme}#input-otp/default`)
    await page.getByRole("textbox").fill("123456")
    await expect(page.getByRole("textbox")).toHaveValue("1234")
    for (const family of ["sheet", "alert-dialog"]) {
      await page.goto(`/style-x?preview&theme=${theme}#${family}/default`)
      const opener = page.locator(`[data-slot="${family}-trigger"]`)
      await opener.click()
      const popup = page.locator(`[data-slot="${family}-content"]`)
      await expect(popup).toBeVisible()
      expect(await popup.evaluate((node) => node.closest("[data-pilot-theme]")?.getAttribute("data-pilot-theme"))).toBe(
        theme
      )
      await page.getByRole("button", { name: family === "sheet" ? "Close" : "Cancel", exact: true }).click()
      await expect(popup).toHaveCount(0)
      await expect(opener).toBeFocused()
    }
    await page.goto(`/style-x?preview&theme=${theme}#select/default`)
    const trigger = page.getByRole("combobox", { name: "Role" })
    await trigger.click()
    await expect(page.locator(`[data-pilot-theme="${theme}"] [data-slot="select-content"]`)).toBeVisible()
    await page.getByRole("option", { name: "Member" }).click()
    await expect(trigger.locator('[data-slot="select-value"]')).toHaveText("member")
    await expect(trigger).toBeFocused()
    await trigger.press("ArrowDown")
    await expect(page.getByRole("listbox")).toBeVisible()
    await page.keyboard.press("Escape")
    await expect(trigger).toBeFocused()
    await page.goto(`/style-x?preview&theme=${theme}#input-group/default`)
    const input = page.getByRole("textbox", { name: "Search" })
    await page.locator('[data-slot="input-group-addon"]').click()
    await expect(input).toBeFocused()
    await input.fill("Search value")
    await expect(input).toHaveValue("Search value")
    expect(await input.evaluate((node) => getComputedStyle(node).borderTopWidth)).toBe("0px")
    expect(await input.evaluate((node) => getComputedStyle(node).boxShadow)).toBe("none")
    await page.goto(`/style-x?preview&theme=${theme}#toggle-group/default`)
    await page.getByRole("button", { name: "Right" }).click()
    await expect(page.getByRole("button", { name: "Right" })).toHaveAttribute("aria-pressed", "true")
    await page.keyboard.press("ArrowLeft")
    await expect(page.getByRole("button", { name: "Left" })).toBeFocused()
    await page.goto(`/style-x?preview&theme=${theme}#item/default`)
    await expect(page.locator('[data-slot="item"]')).toBeVisible()
    expect(await page.locator('[data-slot="item"]').evaluate((node) => node.getBoundingClientRect().width)).toBe(320)
    await page.goto(`/style-x?preview&theme=${theme}#label/default`)
    await expect(page.locator('[data-slot="label"]')).toHaveAttribute("for", "story-label")
  })
}
